image: python:latest

cache:
  paths:
    - ~/.cache/pip

before_script:
  - python -V
  - pip install -r requirements.txt

stages:
  - test
  - style

testing:
  stage: test
  script:
    - coverage run manage.py test killer

pylint:
  stage: style
  script:
    - pylint-fail-under -j 0  --ignore=tests.py, killer/apps.py, killer/admin.py --load-plugins=pylint_django  --fail_under 9.0 killer
pep8:
  stage: style
  script:
  - pycodestyle dbrequests.py killer/views.py killer/tests.py
