image: python:latest

cache:
  paths:
    - ~/.cache/pip

before_script:
  - python -V
  - pip install -r requirements.txt

stages:
  - test
  - style

testing:
  stage: test
  script:
    - coverage run manage.py test killer

pylint:
  stage: style
  script:
    - pylint -j 0 --load-plugins=pylint_django killer
pep8:
  stage: style
  script:
  - pycodestyle .
